#ifndef SOL_INCLUDE__LEXER_LEXER_H
#define SOL_INCLUDE__LEXER_LEXER_H

#include "sol/lexer/token.h"
#include "sol/types.h"

// Lexes a string.
//
// Pass an unsigned long by reference to tk_num to
// get the number of tokens in the token list. It
// can be NULL if not needed.
token_t **sol_lex(const char *input, uint64 *tk_num);

// Automatically destroy all tokens generated by sol_lex.
void sol_cleanup_lex_res(token_t **tokens, uint64 tk_num);

#endif // !SOL_INCLUDE__LEXER_LEXER_H
