#ifndef PLUJA_INCLUDE__PARSER_PARSE_H

#include "pluja/parser/node.h"
#include "pluja/types.h"

// Returns a list with the allocated nodes.
//
// Pass an unsigned long by reference to node_num to
// get the numer of nodes in the node list. It
// can be NULL if not needed.
node_t **plj_parse(token_t **tokens, uint64 tk_num, uint64 *node_num);

// Print the Abstract Syntax Tree generated by plj_parse.
void plj_print_ast(node_t **nodes, size n);

// Automatically destroy all nodes generated by plj_parse.
void plj_cleanup_parse_res(node_t **nodes, uint64 node_num);

#endif // !PLUJA_INCLUDE__PARSER_PARSE_H
