#ifndef SOL_INCLUDE__PARSER_PARSE_H

#include "sol/parser/node.h"
#include "sol/types.h"

// Returns a list with the allocated nodes.
//
// Pass an unsigned long by reference to node_num to
// get the number of nodes in the node list. It
// can be NULL if not needed.
Node **sol_parse(Token **tokens, uint64 tk_num, uint64 *node_num);

// Print the Abstract Syntax Tree generated by sol_parse.
void sol_print_ast(Node **nodes, size n);

// Automatically destroy all nodes generated by sol_parse.
void sol_cleanup_parse_res(Node **nodes, uint64 node_num);

#endif // !SOL_INCLUDE__PARSER_PARSE_H
