#ifndef PLUJA_INCLUDE__LEXER_LEXER_H
#define PLUJA_INCLUDE__LEXER_LEXER_H

#include "pluja/lexer/token.h"
#include "pluja/types.h"

// Lexes a string.
//
// Pass an unsigned long by reference to tk_num to
// get the number of tokens in the token list. It
// can be NULL if not needed.
token_t **plj_lex(const char *input, uint64 *tk_num);

// Automatically destroy all tokens generated by plj_lex.
void plj_cleanup_lex_res(token_t **tokens, uint64 tk_num);

#endif // !PLUJA_INCLUDE__LEXER_LEXER_H
